### PR TITLE
Add fixture and test to show new challenge behavior

### PR DESCRIPTION
**Pull request by simonpercivall**
Fix "native" interpreter challenge parsing after update.

### CODE REVIEW

**Comment by VeNoMouS** [comment]
You didn't fix node etc... also the tests will fail as you didnt alter the fixtures.

**Comment by VeNoMouS** [comment]
I'm Ah you did update fixture.

**Comment by VeNoMouS** [comment]
This was implemented partly using your #223 ticket and some additional changes into the regex, thank you for the PR however

**Comment by simonpercivall** [comment]
@VeNoMouS Thanks! I put it up as a draft PR in the hope that it perhaps speed up your work … seems it may have created more work instead, sorry about that.

**Comment by VeNoMouS** [comment]
LOL all good mate :) , i and im sure the community are grateful to the people who help out all the same ❤️

**Pull request closed without merging**
