### PR TITLE
inherit 'verify' attribute from given Session()

### PR DESCRIPTION
**Pull request by Nandaka**
This is to allow override the cacert.pem, see https://stackoverflow.com/a/33138573

### CODE REVIEW

**Comment by VeNoMouS** [comment]
```python
scraper.adapters['https://'].ssl_context.check_hostname = False
```

**Comment by Nandaka** [comment]
Any reason not to inherit the 'verify' attribute? 

I can set the request.Session() and then set the 'verify' attribute to external cacert.pem from certifii package.
I need to do it this way because cloudscraper doesn't really works if it is being `frozen` using py2exe. It will throw an error due to missing 'cacert.pem'.

**Comment by rnyPlanet** [comment]
@VeNoMouS can you help update challenge?

**Comment by parsa10** [comment]
> ```python
> import cloudscraper
> scraper = cloudscraper.create_scraper()
> scraper.adapters['https://'].ssl_context.check_hostname = False
> scraper.get('https://www.blahblah.com', verify=False)
> ```
> 
> Or
> 
> ```python
> import cloudscraper
> scraper = cloudscraper.create_scraper()
> scraper.adapters['https://'].ssl_context.check_hostname = False
> scraper.get('https://www.blahblah.com', verify='/tmp/ca_bundle.pem')
> ```

This is not working for me , I'm trying to scrap this site : https://zar2film.info/ but i got this error : 
`requests.exceptions.SSLError: HTTPSConnectionPool(host='zar2film.info', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)')))`

**Pull request closed without merging**
