### PR TITLE
Added parameter to change the type of encryption used

### PR DESCRIPTION
**Pull request by felipehertzer**
I was having problems to perform the handshake with some servers because it is using 384bit encryption, so I found a type that solves my problem the "secp384r1". I added the possibility for the user to choose the best algorithm for each use.

The main problem I had was handshake errors like:
`(Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE]) sslv3 alert handshake failure (_ssl.c:1108)'))`

### CODE REVIEW

**Comment by VeNoMouS** [comment]
> Hello sir @felipehertzer just have tested it. The repo look patched can't solve cloudflare challenge (v1)
> Also the cookie ''cfduid'' has beem removed since 2 month ago.
> Do u can fix it to work on new challenge ?
> 
> Thanks

image

**Comment by VeNoMouS** [comment]
@felipehertzer while your're on the right track, your also WAY off ... this will only work for specific sites with specific settings setup... additionally this will cause you problems if your abusing cloudflare BFM...

**Comment by felipehertzer** [comment]
Sorry for the branch. I changed my script to brainpoolP256t1 seemed to work correctly so far, but I don't know if you know if this might not work.

**Comment by joshcoales** [comment]
> Also if you want me to implement this.... i suggest not doing a PR to the master branch... that is what the `dev` branch is for.

Seems like you have to correct people often on that, might be worth adding a little [contributors file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) which explains that

**Pull request merged**
