### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by aminprox**
- Fix the error when Cloudflare returns 503 status code

### CODE REVIEW

**Comment by VeNoMouS** [comment]
I don't see any benefit to your PR.... can you please explain your thinking here?

**Comment by aminprox** [comment]
In some conditions the Cloudflare might return 503 error for the challenge page. It was supposed to handle those.

**Comment by miigotu** [comment]
@aminprox The collect-all Exception right below your PR addition does exactly the same thing.

**Comment by aminprox** [comment]
> @aminprox The collect-all Exception right below your PR addition does exactly the same thing.

Not exactly as It checks for 503 error code first.
Anyway, this PR is way too old and I'm not sure if it does anything anymore.

**Pull request closed without merging**
