### PR TITLE
Async integration

### PR DESCRIPTION
**Pull request by Nachtalb**
As it is not possible to create issues I'll ask here.

I am coming from [aiocfscrape](https://github.com/pavlodvornikov/aiocfscrape) which was an async approach/reimplementation of [cfscrape](https://github.com/Anorov/cloudflare-scrape). `cfscrape` seems to be dead nowadays. Thus `aiocfscrape` would now do the bypassing by itself or rebasing on a new project. Either way, it would need to be rewritten. 

But as you seem to be fond of supporting various environments (eg. multiple different JS engine and captcha services).

Thus I propose to add async support with `aiohttp` directly to this repo instead of leeching off this one.

Architecturally I'd put the different implementations (requests, aiohttp) similarly as the JS engine and captcha service into one place, where then the user can say he wants either one of them. The difference would be however that the user can tell the session `async=True` and it'll then get the async implementation instead of the requests one. Another way would be to just create a new module and tell the user to import from `...async.CloudScraper` instead. 
This would also need second implementations of eg. the node js engine as we'd have to use [async subprocesses](https://docs.python.org/3/library/asyncio-subprocess.html) instead of the usual one.

This would also mean the python version compatibility wouldn't be 3.x but rather at least 3.5.x or rather even 3.6 as 3.5 actually [reached its end of life](https://pythoninsider.blogspot.com/2020/10/python-35-is-no-longer-supported.html).

I'd be glad to create/maintain the async implementation.

### CODE REVIEW

**Comment by welmd** [comment]
Traceback (most recent call last):
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.

**Comment by iclapcheeks** [comment]
I was looking for something exactly like this, the only thing that I was bummed about was that there was no async support! I think this will be a great contribution to this package.

**Comment by Josh-Payne** [comment]
Any resolution planned here?

**Comment by rafalkrupinski** [comment]
Pity it was closed without a discussion, but since CS is deeply integrated with sync-only requests, it would require a complete rewrite/clone of the current codebase.

One option for a rewrite, if one was so inclined, would be making it [IO agnostic](https://sans-io.readthedocs.io/), except it wouldn't convert objects and bytes, but rather plain request and response objects to and from CF-compatible ones. Since it's pure CPU operation, no need for async.

It would still need a thin layer around the target IO implementation (requests, aiohttp, httpx) to smooth out API incompatibilities and handle setting up sessions (i.e. `requests.Session.mount`), but that would be much easier to maintain than a full clone.



As for me, I just pass my calls in anyio.to_thread.run_sync and it's alright.

**Pull request closed without merging**
