### PR TITLE
Fix issues with proxied anticaptcha tasks

### PR DESCRIPTION
**Pull request by fqrious**

### CODE REVIEW

**Comment by VeNoMouS** [comment]
hi @fqrious couple things

a) can you submit this on your own PR
b) submit to dev not master

**Comment by fqrious** [comment]
changed

**Comment by VeNoMouS** [comment]
Cheers i'll cherry pick and test in a bit and if good ill merge it in :) thanks for contributing either way mate :) , ive had my plate a bit full to fix that

**Comment by VeNoMouS** [comment]
@fqrious thanks for that, can confirm it works, i might modify where you define the user_agent back into `Challenge_Response()`

**Comment by andress134** [comment]
@VeNoMouS sorry because im writed here, i try to scrape page welovecloudflare.de and received this error.
Debug Error: 'utf-8' codec can't decode byte 0xec in position 1213: invalid continuation byte

i think is changed something,  here soime info about update https://github.com/scaredos/cfresearch
Do u still offer updates for cloudscraper lib?

**Comment by ermaxinc** [comment]
What mean "Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version."
Where get/buy paid version?

**Pull request merged**
